sudo: required
services:
  - docker

before_install:
  - docker build -t isometria/dkw-10-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true isometria/dkw-10-client npm test -- --coverage

after_success:
  - docker build -t isometria/dkw-10-api ./api
  - docker build -t isometria/dkw-10-client ./client
  - docker build -t isometria/dkw-10-nginx ./nginx
  - docker build -t isometria/dkw-10-worker ./worker

  # Take those images and push to dockerhub
  - echo "asdf" | docker login -u "vafdsfda" --password-stdin

  - docker push isometria/dkw-10-api
  - docker push isometria/dkw-10-client
  - docker push isometria/dkw-10-nginx
  - docker push isometria/dkw-10-worker