sudo: required
services:
  - docker

before_install:
  - docker build -t isometria/dkw-10-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true isometria/dkw-10-client npm test -- --coverage

after_success:
  - docker build -t isometria/dkw-10-api:latest ./api
  - docker build -t isometria/dkw-10-client:latest ./client
  - docker build -t isometria/dkw-10-nginx:latest ./nginx
  - docker build -t isometria/dkw-10-worker:latest ./worker

  # Take those images and push to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push isometria/dkw-10-api:latest
  - docker push isometria/dkw-10-client:latest
  - docker push isometria/dkw-10-nginx:latest
  - docker push isometria/dkw-10-worker:latest